services:
  - type: web
    name: dvoranko-backend
    env: docker
    dockerContext: source_code/backend/dvoranko-backend
    region: frankfurt
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: GOOGLE_OAUTH2_ID
        sync: false
      - key: GOOGLE_OAUTH2_SECRET
        sync: false

  - type: web
    env: static
    name: dvoranko
    rootDir: source_code/frontend/dvoranko-frontend
    region: frankfurt
    buildCommand: npm install && npm run build
    staticPublishPath: dist
