services:
  - type: web
    name: dvoranko
    env: docker
    rootDir: .
    dockerContext: .
    region: frankfurt
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: GOOGLE_OAUTH2_ID
        sync: false
      - key: GOOGLE_OAUTH2_SECRET
        sync: false
