services:
  - type: web
    name: dvoranko-backend
    env: docker
    dockerContext: backend/dvoranko-backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dvoranko-db.internal:5432/dvoranko
      - key: SPRING_DATASOURCE_USERNAME
        value: postgresuser
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: GOOGLE_OAUTH2_ID
        sync: false
      - key: GOOGLE_OAUTH2_SECRET
        sync: false

  - type: web
    name: dvoranko-frontend
    env: node
    rootDir: frontend/dvoranko-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: .
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://dvoranko-2.onrender.com
